[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore TGBotTest.sln",
  "dotnet build TGBotTest/TGBotTest.csproj -c Release",
  "dotnet publish TGBotTest/TGBotTest.csproj -c Release -o /app"
]

[start]
cmd = "dotnet /app/TGBotTest.dll"