[phases.setup]
nixPkgs = ["dotnet-sdk_8", "icu", "zlib", "openssl"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish -c Release -o /app"]

[start]
cmd = "dotnet /app/TGBotTest.dll"